### ISSUE TITLE
[Feature Request] Install Windows 10 SDK in OneBranch

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4225]
steps: 
- script: choco install windows-sdk-10.1 --version=10.1.17763

**Comment by trwalke** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4228

**Comment by gladjohn** [comment]
```
            - task: PowerShell@2
            displayName: Install Chocolatey
            inputs:
              targetType: 'inline'
              script: |
                Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))   
   
          - task: PowerShell@2
            displayName: Install Windows 10 SDK (version 17763)
            inputs:
              targetType: 'inline'
              script: |
                choco install windows-sdk-10-version-1809-all -y

```
