### ISSUE TITLE
[Bug] Pipeline failure - Expired PAT

### ISSUE THREAD

**Issue by johnypony3** [AzureAD/microsoft-authentication-library-for-dotnet#5043]
### Library version used

N/A

### .NET version

N/A

### Scenario

Other - please specify

### Is this a new or an existing app?

None

### Issue description and reproduction steps

This code is failing [the pipeline](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/actions/runs/12529767055), no deployments are happening.

```yaml
        - name: Azure Pipelines Action
          uses: Azure/pipelines@354dddefceb0b503a61338ca81e4091eae3bc84f # v1
          with:
            azure-devops-project-url: https://identitydivision.visualstudio.com/IDDP
            azure-pipeline-name: 'MSAL.NET-OneBranch-Release-Official'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
```

### Relevant code snippets

```csharp
﻿{
    "$id": "1",
    "customProperties": {
        "Descriptor": null,
        "IdentityDisplayName": null,
        "Token": null,
        "RequestedPermissions": 0,
        "NamespaceId": "00000000-0000-0000-0000-000000000000"
    },
    "innerException": null,
    "message": "Access Denied: The Personal Access Token used has expired.",
    "typeName": "Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi",
    "typeKey": "AccessCheckException",
    "errorCode": 0,
    "eventId": 3000
}
```

### Expected behavior

The pipeline does not fail.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Solution and workarounds

Generate new PAT and update value. Add monitoring to deployment.
